name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo_mysql, xml, curl, zip, bcmath
          ini-values: display_errors = On
            error_reporting = E_ALL

      - name: "nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: "npm"
        run: npm install

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: environment variables
        run: cp .env.example .env

      - name: "npm run build"
        run: npm run build

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Migrate Database
        run: php artisan migrate --force

      - name: Optimize Application
        run: php artisan optimize:clear

      - name: Hostinger SSH Deployment
        uses: easingthemes/ssh-deploy@main
        with:
          SOURCE: "."
          SSH_PRIVATE_KEY: ${{ secrets.HOSTINGER_SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOSTINGER_SSH_HOST }}
          REMOTE_USER: ${{ secrets.HOSTINGER_SSH_USER }}
          REMOTE_PORT: ${{ secrets.HOSTINGER_SSH_PORT }}

          TARGET: ${{ secrets.HOSTINGER_SSH_TARGET_PATH }}
          EXCLUDE: "/node_modules, /storage, /bootstrap/cache, /public/storage, .env"

          SCRIPT_AFTER: |
            cd ${{ secrets.HOSTINGER_SSH_TARGET_PATH }}
            git pull origin main
            php artisan migrate
            php artisan optimize:clear



